### ISSUE TITLE
Extend community driver 

### ISSUE THREAD

**Issue by LensHunnel** [napalm-automation/napalm#1245]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [] No

### napalm version

```
napalm==2.5.0
napalm-aos==0.2.0
napalm-huawei-vrp==0.1.5

```

### Network operating system version

```
Alcatel-Lucent Enterprise OS6860E-U28 8.4.1.233.R02 
```

### Steps to Reproduce the Issue

I've followed the tutorial to extend a driver it's working with core driver eg: IOSDriver

There is a way to extend a community driver ?

**Comment by network-shark** [comment]
You can create a pull request for each driver .

All Community Driver
https://github.com/napalm-automation-community?page=1

Drivers
https://github.com/napalm-automation-community/napalm-aos
https://github.com/napalm-automation-community/napalm-huawei-vrp

**Comment by LensHunnel** [comment]
It isn't the same thing, thoses drivers are working for some os versions but with minor changes (like with the extends driver feature) I can add support for others OS versions.

**Comment by mirceaulinic** [comment]
Hi @LensHunnel:

> thoses drivers are working for some os versions but with minor changes (like with the extends driver feature) I can add support for others OS versions.

I think this falls exactly under what @network-shark mentioned: I'd recommend you to work it out in the existing public drivers for the benefit of the community at large. The minor changes can be modeled depending on the device properties as we do, for example, in the core NAPALM driver for IOS or Junos (e.g., https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L398).

But to answer your initial question, yes, you can always extend the community drivers in the exact same way. For example, instead of:

```python
from napalm.ios.ios import IOSDriver
class CustomIOSDriver(IOSDriver):
```

You'd have the following for the napalm-aos community driver:

```python
from napalm_aos.aos import AOSDriver
class CustomAOSDriver(AOSDriver)
```
