### ISSUE TITLE
IOS XE NETCONF cli-config-data-block, candidate config diffs etc

### ISSUE THREAD

**Issue by indy-independence** [napalm-automation/napalm#1333]
### IOS XE NETCONF cli-config-data-block, candidate config diffs etc

This is not a specific bug so tell me if I'm in the wrong place, but I think it could be good to have a place to track/discuss the state of driver for IOS XE. It seems like IOS XE (unlike classic IOS) has good support for candidate configurations via NETCONF that does not require you to SCP textfiles and so on. From what I can find there is "cli-config-data-block" command that could be used to send in a CLI config, there is candidate config with a Validate command, and there is even support for confirmed commit/rollback. Is this not a better option than using the current way to replace/diff configs? It seems like IOS XE became the default OS for Cisco campus networks in 2013 when 3850 launched, so for me I think it's more important to have good support for current devices rather than having good support for really old legacy devices if that is a concern here

**Comment by mirceaulinic** [comment]
Hi @indy-independence. The current driver for IOS aims to cover IOS-XE as well, and it is not based on NETCONF. If you would like to contribute however, we can create a repository for you under the [napalm-automation-community](https://github.com/napalm-automation-community) where you can start working on a NETCONF-based driver for IOS-XE. It might be a good idea to ask in Slack or other channels to collaborate with other users on that. See also: https://napalm.readthedocs.io/en/latest/contributing/drivers.html#contributing-drivers -- if a driver get significant traction and proves there's a enough contribution from the maintainers, it can be promoted to be included into the NAPALM core.
Let me know if you have any questions.

**Comment by ktbyers** [comment]
You should also make sure if you go down this road that the NETCONF IOS-XE is feature complete (or very close to feature complete) and by this I mean that almost `everything` that can be configured via the CLI can also be configured via NETCONF. Otherwise, you start to get into needing two mechanisms for configuration: NETCONF + legacy-cli.

Also you would probably need to research at what IOS-XE version the implementation of NETCONF was sufficiently good to be used for configuration (i.e. you would probably need legacy CLI for OS versions older than X).

Happy to be wrong on both of the above, but I definitely think we would run into issues with both of these items (given my understanding of the situation).

Let me know what you find if you head down this road.


Regards, Kirk

**Comment by indy-independence** [comment]
Yes I share the same concern about feature completeness of the NETCONF implementation, that's why I'm suggesting use of the "cli-config-data-block" to start. It looks like it accepts the same old CLI commands, so you can just have the same Jinja2 templates etc as before but send it via another protocol I think. Or am I missing something here?

**Comment by ktbyers** [comment]
I haven't looked into it...so can't comment much. Can you support full configuration replace (i.e. replace everything in the config using this mechanism)? Also is there a reasonable way of generating human readable diffs using this mechanism?

The key thing would be to build all of the NAPALM configuration methods.
