### ISSUE TITLE
[Feature request] better ```config_replace``` for nxos

### ISSUE THREAD

**Issue by haddystuff** [napalm-automation/napalm#1894]
### Description of Issue/Question

NXOS drivers implements config_replace feature using ```rollback``` command which works fine, but has some gotchas which mentioned in napalm docs. Staring from 7th release nxos supports ```config replace``` command which does the same thing, but it doesn't have all of those irritating gotchas. Maybe it's we can change command for config_replace feature in NXOSDriver and NXOSSSHDriver?
More info about ```config replace``` [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/system-management/b-cisco-nexus-9000-series-nx-os-system-management-configuration-guide-93x/b-cisco-nexus-9000-series-nx-os-system-management-configuration-guide-93x_chapter_011000.html)

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [] No

### napalm version
```
napalm==4.0.0
```

**Comment by ktbyers** [comment]
I don't think this is really viable due to Cisco only making this available to a subset of Cisco NX-OS products.

```
The configuration replace feature is supported on Cisco Nexus 3000 Series and Cisco Nexus 9000 Series switches.
```

So that would really imply that we needed to maintain and test two different solutions.

I could possibly see doing it--if it provided us with a reasonable way to do the commit-confirm feature on NX-OS which IIRC isn't really viable with our current solution.

But even then it would still probably imply that we maintain two solutions--one using rollback and one using `configure replace` which I am not super keen on doing.
