### ISSUE TITLE
Config not applied on Cisco IOS

### ISSUE THREAD

**Issue by t2d** [napalm-automation/napalm#209]
I'm usinge the Cisco 897VAW. The commandline seems to work fine:
```
cl_napalm_configure --user admin --vendor ios --strategy replace running-config gw 
Enter password: 
interface GigabitEthernet1
 +authentication event fail action next-method
 +authentication event server dead action authorize vlan 3
 +authentication event no-response action authorize vlan 3
 +authentication event server alive action reinitialize
 +authentication host-mode multi-host
 +authentication order dot1x
 +authentication priority dot1x
 +authentication port-control auto
 +authentication periodic
 +dot1x pae authenticator
 +dot1x timeout server-timeout 3
 +dot1x timeout tx-period 3
 +dot1x timeout supp-timeout 3
 +dot1x max-req 3
 +dot1x max-reauth-req 3
 +no shutdown
```
But when I check on the device, the config is actually still the old one:
```
#show running-config | section interface GigabitEthernet1
interface GigabitEthernet1
 no ip address
 spanning-tree portfast
```
This also happens with napalm-ansible.

**Comment by dbarrosop** [comment]
@ktbyers can you help troubleshoot this?

@t2d have you tried with python code instead of with ansible or the CLI?

**Comment by ktbyers** [comment]
@dbarrosop @t2d This worked for me on a Cisco 881 using latest Napalm code.

```
$ python ~/napalm/napalm/clitools/cl_napalm_configure.py --user pyclass --vendor ios --strategy replace initial.conf 1.1.1.1
Enter password: 
+logging buffered 20000
-logging buffered 221122
```

It sounds like it is most likely one of the following:

> 'archive' command is missing from the configuration.

```
archive 
    path flash:myfile-cfg              # some path and file name
```

Without this you get the following:

```
pynet-rtr1#configure replace flash:candidate_config.txt force revert trigger error
%Please turn config archive on
```

> Or it might be your version of IOS doesn't support 'configure replace'

What version of IOS are you running? Does this command exist in IOS?

configure replace flash:candidate_config.txt force revert trigger error



@dbarrosop Where should this be documented at?

**Comment by t2d** [comment]
I'm running version 15.5 and it support `configure replace`.
```
#show running-config | section archive
archive
 path flash:archive
 write-memory
```
There are even archive files:
```
   17  -rw-       16766   Mar 2 2016 07:49:12 +01:00  archive-Mar--2-06-49-11.863-0
   18  -rw-       21744   Mar 2 2016 07:55:22 +01:00  archive-Mar--2-06-55-23.384-1
```

**Comment by t2d** [comment]
`--strategy merge` seems to work just fine.
```
#  configure replace flash:candidate_config.txt force revert trigger error
%The input file is not a valid config file.
```
That's the problem! Would be nice, to expose this somehow. And I'm not sure, why napalm constructs an invalid config file, but that could totally be my fault, since I used the config file for manual merging until now.

**Comment by dbarrosop** [comment]
@t2d agreed, we should catch that error somehow. @ktbyers, is this something you could look into? However, napalm doesn't construct any configuration file, it just uploads whatever you have. If you constructed the file by just copy pasting the output of `show running-config` it might be that there is some header introduced by IOS that they don't like. Try removing comments or if there is any `version`. If you can share the file I might be able to try (remove any sensitive information first ;) )

**Comment by ktbyers** [comment]
@dbarrosop @t2d 

I have a bit of reluctance to try to catch many errors on IOS since there could potentially be numerous different variations on error strings (which is a lot of string processing).

Though maybe we should try to catch errors due to failed configure replace operations (and potentially failed configure merge operations).

Related to this is whether a failed configure replace operation should generate an exception (this could cause negative side effects with Ansible and NAPALM for IOS).

At a minimum this should be logged so that issues are easier to see.


Related to this, I could not on IOS construct a valid configuration by doing show run. This was due to formatting issues from Cisco related to the self-signed certificate. Basically at one point Cisco used a tab character (\t) and trying to copy-paste this converted it to spaces. Consequently, in order to get a valid base config, I had to SCP the file from the device.

**Comment by dbarrosop** [comment]
> I have a bit of reluctance to try to catch many errors on IOS since there could potentially be numerous different variations on error strings (which is a lot of string processing).

All the errors start with `%` right? Why not just catch that and pass the rest as a message to the exception? That might be interesting to do directly on netmiko, don't you think? Having like a GenericCLIException or something like that.

> Related to this is whether a failed configure replace operation should generate an exception (this could cause negative side effects with Ansible and NAPALM for IOS).

Yes, that should definitively happen. There are two exceptions for that actually: ReplaceConfigException and MergeConfigException. Ansible or any other code should catch that and handle it properly.

**Comment by ktbyers** [comment]
Yes, that is fair enough I could possibly catch on the '%'. It usually isn't this easy, however (i.e. I have warning alarms going off in my head).

Netmiko's paradigm is to provide you the output back. So if you put in an invalid command, it will show you the CLI error. You can then raise an exception if you want (i.e. you can handle the errors in your Python code).

NAPALM is obviously a different context since it is higher level.

I will create an issue for this and assign it to me since this should be handled better.
