### ISSUE TITLE
help for support other device!

### ISSUE THREAD

**Issue by aihuasxy** [napalm-automation/napalm#342]
hi，I am newbie to napalm and have read some document and code of napalm.

I have a question.

If I want to add support for other devices like zxr10 of ZTE,  how can I know whether its possible to extend napalm.
Does it need network devices have the ability of replacing configure wholly (cisco ios using configure replace).
If the device only support CLI , does it can't use panpalm?

**Comment by dbarrosop** [comment]
Hello @aihuasxy,

> If I want to add support for other devices like zxr10 of ZTE, how can I know whether its possible to extend napalm.

Any device can be added to napalm, it might be easier or harder depending on the device API (if any) or how feature-rich their CLI is but it should be doable to add nay device.

> Does it need network devices have the ability of replacing configure wholly (cisco ios using configure replace).

No, not all the features are mandatory. That's why we have this page:

https://napalm.readthedocs.io/en/latest/support/index.html

> If the device only support CLI , does it can't use panpalm?

Yes, there are a few examples of devices supported by napalm that use netmiko or other form of screen scraping because an API is not available, most notably IOS : )

If you want to start playing, I suggest you this repo:

https://github.com/napalm-automation/napalm-cookiecutter

As it will help you getting started with a skeleton. Then, the tricky part of integrating a driver with napalm is the testing framework but there are plenty of examples out there and we can help with that anyway.

Regards!
David

**Comment by aihuasxy** [comment]
Thanks for your detailed answers。
