### ISSUE TITLE
Project Name Issue

### ISSUE THREAD

**Issue by sumperson** [napalm-automation/napalm#409]
### Description of Issue/Question

The project is named after an anti-personnel weapon responsible for quite a bit of suffering and death, as exemplified by that famous photo of Phan Thi Kim Phuc. You can quickly find loads of other examples of the impact of napalm with a google image search.

I'm sure there are plenty of projects named after iconic weapons but does yours need to be? You're not getting any help with search engine rankings with this name. Plenty of living people were injured by napalm and plenty of living people have acquaintances and family members who were killed or injured by napalm and they may not look favorably on such a casual use of the name.

I do understand if this seems like runaway political correctness and I expect this issue will be rejected, but I'm still opening it because the name alone is stopping me from suggesting this software at work. The name may be holding the project back in other ways.

**Comment by dbarrosop** [comment]
Thank you for your comment. I understand the name could be offensive for some people and I am really sorry for that. What I am about to say it's just context/history, I am not trying to defend the name or anything.

The project started as an internal tool long ago, as you can imagine, being an internal project the name never got a second thought and napalm was mostly a joke due to the frustrations we had with working with several vendors. After talking with several people in the community we realized there was common ground to work together so this internal tool was shared on github in a private repo so we could start collaborating. Before we realized, the tool had grown quite a bit and there was a bunch of people from different organizations working on it so we just decided to make the repo public and start sharing it with the community. Up to this point, nobody had really cared about the name, we were just fixing a problem without caring about what seemed like an non-important detail at the time, so the name just carried on. A couple of years later the project is quite popular and I understand it doesn't have the best name, believe me if I tell you that if I had known 3 years ago the project was going to grow so much I would have picked a more neutral name.

> I do understand if this seems like runaway political correctness and I expect this issue will be rejected

Regardless of the reason I think your points are still valid and it's not going to be rejected because we don't agree with you, I have considered myself this topic a couple of times, but changing the name of a project is a titanic effort that we probably can't afford to do ourselves (update docs, references in code, variables, classes, readmes, domain names, etc). This might sound as an excuse but this is an opensource project lead by volunteers with no political affiliations, no backing from any company or foundation and no funding so a task like that is hard to execute because it's a task that has to be done during our free time at the expense of bugfixes and new features. If you, or someone else, would be willing to volunteer to help out with this, we'd be willing to discuss this endeavor.

Thanks again for raising this topic.

**Comment by jejenone** [comment]
I tend to agree with @sumperson here. I've been thinking about it many times, and now that it's a much more public project, the name has become a burden.

Maybe we could start by suggesting other names ?

**Comment by dbarrosop** [comment]
I'd rather not start discussing names until I see the commitment of an individual or group of individuals to form a plan and carry it out.

**Comment by sumperson** [comment]
Thanks for considering it. I know a rename would be a big challenge because I'm trying it myself in working copies of the napalm repos and finding lots of things are easily missed and need to be reconnected. For my testing purposes I'm just using the dummy name ANP (automated network programmer) but that's not a good name. I may not be the person to spearhead this, but I'll keep working at it in my free time.

Everyone who knows what they are talking about says that being an open source maintainer for any significant amount of time is really really hard so I appreciate the open and positive way you're looking at this issue.

**Comment by dbarrosop** [comment]
I am closing this one for the time being. If someone is interested in carrying out this task feel free to reopen an let us know.

Thanks.
