### ISSUE TITLE
Using ipaddress module

### ISSUE THREAD

**Issue by KalleDK** [napalm-automation/napalm#711]
Have there been a discussion about the ipaddress module?

https://docs.python.org/3/library/ipaddress.html

So that instead of strings we can use actually adresses / interfaces / networks?

This would properly ruin backward compability, which I know a lot is fond of - but it could work with an option or something like that, (as in to enable it)

**Comment by ktbyers** [comment]
Why? `netaddr` is working fine for what we need it for?

I am not seeing it being worth the work to do this.

**Comment by ktbyers** [comment]
Yes, I think the logical item to return here is a string, not a custom class.

You could do this in your code, but we probably wouldn't do this NAPALM. Note, NAPALM needs to interact with other upstream libraries (like Ansible, Salt, StackStorm, Brigade) so returning IP address objects instead of strings would likely break things.

**Comment by KalleDK** [comment]
str(ip) would give the string you now are returning, but I do agree that it would break a lot upstream. 

And ut is what I'm doing right now - wrapping all the calls and return with the ipaddress module.

But it might just be me :)

**Comment by ogenstad** [comment]
A problem is that the ip address object wouldn't be serializable, so if that was used instead of a string things would break.

**Comment by KalleDK** [comment]
Aaah your right that would be a pain without custom handles. Well thanks for the discussion :)
