### ISSUE TITLE
please fix issues in setup.py (pip.req is not available in pip 10+

### ISSUE THREAD

**Issue by kqchen34** [napalm-automation/napalm#862]
lots of naplam libs like napalm-base / napalm-eos .....
still has setup.py with importing pip.req, which is not available in pip verion 10+
refer to https://stackoverflow.com/questions/25192794/no-module-named-pip-req:

Can we update those libs' setup.py, to change:
from pip.req import parse_requirements
install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
reqs = [str(ir.req) for ir in install_reqs]

to:
with open("requirements.txt", "r") as fs:
    reqs = [r for r in fs.read().splitlines() if (len(r) > 0 and not r.startswith("#"))]

So that the install would not fail when pip 10+ is being used?

Thanks

**Comment by ktbyers** [comment]
@kqchen34 napalm-base, napalm-eos were deprecated quite a while ago.

You need to `pip install napalm` and use that package instead.

Basically, we had to reunify napalm into a single package instead of separate packages as the maintenance was too much of problem (this is for the core napalm drivers: eos, ios, junos, iosxr, nxos, and nxos_ssh).


Kirk
